config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  delete '/auth/signout', to: 'sessions#destroy'

  root 'welcome#index'

  match ':controller(/:action(/:id(.:format)))', :via => :all

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :name

  has_attached_file :logo, :style => { :medium => "300x300>", :thumb => "100X100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_hash)
    user = where( :fb_uid => auth_hash[:uid] ).first_or_initialize
    user.name = auth_hash[:info][:name]
    user.email = auth_hash[:info][:email]
    user.fb_token = auth_hash[:credentials][:token]
    user.fb_expires_at = Time.at(auth_hash[:credentials][:expires_at])
    user.save!
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, :only => [ :show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to :action => :index
      flash[:notice] = "event was successfully created"
    else
      render :action => :new
    end
  end

  def show
    @page_title = @event.name
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to :action => :show, :id => @event
      flash[:notice] = "event was successfully updated"
    else
      render :action => :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to :action => :index
    flash[:alert] = "event was successfully deleted"
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :logo)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    Rails.logger.debug( env["omniauth.auth"] )
    user = User.from_omniauth(auth_hash)

    reset_session
    session[:user_id] = user.id

    flash[:notice]='Login successfully'
    redirect_to root_path
  end

  def failure
    Rails.logger.debug( env["omniauth.auth"] )

    flash[:alert]='Login failed'
    redirect_to root_path
  end

  def destroy
    reset_session

    flash[:notice]='Logout successfully'
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <div class="form-group">
    <%= f.file_field :logo %>
  </div>

<% if @event.errors.any? %>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

app/views/events/edit.html.erb
<%= form_for @event, :url => { :controller => 'events', :action => 'update', :id => @event }, :html => { :multipart => true } do |f| %>

  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<table>
  <% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= link_to "Show", :controller => 'events', :action => 'show', :id => event %></td>
    <td><%= link_to "Edit", :controller => 'events', :action => 'edit', :id => event %></td>
    <td><%= link_to "Delete", :controller => 'events', :action => 'destroy', :id => event %></td>
  </tr>
  <% end %>
</table>

<%= button_to "New Event", :controller => 'events', :action => 'new' %>

app/views/events/new.html.erb
<%= form_for @event, :url => { :controller => 'events', :action => 'create' } do |f| %>

  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>

<%= link_to image_tag(@event.logo.url(:thumb) ), @event.logo.url %>
<p><%= link_to "Back to Index", :controller => 'events', :action => 'index', class: "btn btn-primary" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wk5 Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>
<p style="color: red"><%= flash[:alert] %></p>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<% if current_user %>
  Hi, <%= current_user.name %>
  <br>
  <%= link_to "My Events", :controller => 'events', :action => 'index' %>
  <%= link_to "Logout", auth_signout_path, :method => :delete %></a>
<% else %>
 <%= link_to "Facebook Login", "/auth/facebook" %></a>
<% end %>